### ISSUE TITLE
Logging with AUC and parameters

### ISSUE THREAD

**Issue by tbrittoborges** [Kingsford-Group/scallopadvising#1]
I successfully used scallopadvising (with Scallop) to optimise the parameters for a series of replicated experiments. Naturally, I found that the generated GTF files are slightly different among the replicates. I would find useful to have the AUC and parameters values logged somewhere, so I can figure out where these differences are coming from.

**Comment by danfdeblasio** [comment]
Hi Thiago, I have added the ability to specify a log file using a flag (`-log_file`), right now it outputs a TSV file with two columns, the input configuration filename and the AUC value of the assembly generated. Thanks for the suggestion! Please feel free to let me know if you run into anything else that may be helpful.

**Comment by tbrittoborges** [comment]
Hi Dan, 

Thank you so much for your prompt action. I have another suggestion, but I will leave it for later.
